# Generated by Django 3.2.9 on 2021-11-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_restaurants_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-pk']},
        ),
    ]
