# Generated by Django 3.2.3 on 2021-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kink', '0002_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_seen',
            field=models.FloatField(default=0, null=True),
        ),
    ]
