# Generated by Django 3.2.6 on 2021-11-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_grammar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(default='Add Title', max_length=200),
        ),
    ]
