# Generated by Django 3.2.6 on 2021-11-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_grammar', '0002_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
