# Generated by Django 3.2.9 on 2021-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_grammar', '0003_chapter_slno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['slno']},
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='page_no',
            field=models.IntegerField(default=0),
        ),
    ]
